CREATE TABLE BATCH_JOB_INSTANCE  
(
    JOB_INSTANCE_ID NUMBER(19,0)  PRIMARY KEY,
    VERSION NUMBER(19,0),
    JOB_NAME VARCHAR2(100) NOT NULL,
    JOB_KEY VARCHAR2(32) NOT NULL,
    constraint UQ_BJI_JOB_INST unique (JOB_NAME, JOB_KEY)
);
