CREATE TABLE REPORT_DATA_TABLE
   (
    RDT_ID NUMBER NOT NULL PRIMARY KEY,
    RDT_JE_ID NUMBER,
    RDT_DATA_SOURCE VARCHAR2(1024),
    RDT_ACUITY_ENTITIES VARCHAR2(255),
    RDT_NUM_SUBJECT_SOURCE NUMBER,
    RDT_NUM_SUBJECTS_ACUITY NUMBER,
    RDT_NUM_EVENTS_UPLOADED NUMBER,
    RDT_RAG_STATUS VARCHAR2(5),
    FOREIGN KEY (RDT_JE_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
   );
