/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 02:29:23 PM MSK 
//

package com.acuity.visualisations.transform.rule;

import com.acuity.visualisations.batch.holders.configuration.IColumnRule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p/>
 * Java class for ColumnRule complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ColumnRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://visualisations.acuity.com/DataTransformation}NamedRule">
 *       &lt;sequence>
 *         &lt;element name="mapper" type="{http://visualisations.acuity.com/DataTransformation}Mapper" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="field" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fmtname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fmtdefault" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="helper" type="{http://visualisations.acuity.com/DataTransformation}parserRule" default="MonthFirst" />
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="part" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="aggrFunction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="radio" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnRule", propOrder = {"mapper"})
public class ColumnRule extends NamedRule implements IColumnRule {

    protected Mapper mapper;
    @XmlAttribute
    protected String field;
    @XmlAttribute
    protected String fmtname;
    @XmlAttribute
    protected String fmtdefault;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected ParserRule helper;
    @XmlAttribute(name = "default")
    protected String _default;
    @XmlAttribute
    protected Boolean part;
    @XmlAttribute
    protected Boolean isSubjectField;
    @XmlAttribute
    protected String aggrFunction;
    @XmlAttribute
    protected Boolean radio;

    private String description;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getExcludingValues() {
        if (excludingValues == null) {
            excludingValues = new ArrayList<>();
        }
        return excludingValues;
    }

    public void setExcludingValues(List<String> excludingValues) {
        this.excludingValues = excludingValues;
    }

    @XmlTransient
    private List<String> excludingValues;

    public Mapper getMapper() {
        return mapper;
    }


    public boolean getSubjectField() {
        return isSubjectField != null ? isSubjectField : false;
    }

    public void setSubjectField(boolean subjectField) {
        isSubjectField = subjectField;
    }

    /**
     * Sets the value of the mapper property.
     *
     * @param value allowed object is {@link Mapper }
     */
    public void setMapper(Mapper value) {
        this.mapper = value;
    }

    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     *
     * @param value allowed object is {@link String }
     */
    public void setField(String value) {
        this.field = value;
    }

    public String getFmtname() {
        return fmtname;
    }

    /**
     * Sets the value of the fmtname property.
     *
     * @param value allowed object is {@link String }
     */
    public void setFmtname(String value) {
        this.fmtname = value;
    }

    public String getFmtdefault() {
        return fmtdefault;
    }

    /**
     * Sets the value of the fmtdefault property.
     *
     * @param value allowed object is {@link String }
     */
    public void setFmtdefault(String value) {
        this.fmtdefault = value;
    }

    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    public ParserRule getHelper() {
        if (helper == null) {
            return ParserRule.MONTH_FIRST;
        } else {
            return helper;
        }
    }

    public void setHelper(ParserRule value) {
        this.helper = value;
    }

    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDefault(String value) {
        this._default = value;
    }

    public Boolean isPart() {
        return part;
    }

    /**
     * Sets the value of the part property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setPart(Boolean value) {
        this.part = value;
    }

    public String getAggrFunction() {
        return aggrFunction;
    }

    /**
     * Sets the value of the aggrFunction property.
     *
     * @param value allowed object is {@link String }
     */
    public void setAggrFunction(String value) {
        this.aggrFunction = value;
    }

    public boolean isRadio() {
        if (radio == null) {
            return false;
        } else {
            return radio;
        }
    }

    /**
     * Sets the value of the radio property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setRadio(Boolean value) {
        this.radio = value;
    }

}
