/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 02:29:23 PM MSK 
//


package com.acuity.visualisations.transform.rule;

import com.acuity.visualisations.mapping.entity.FileStandard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DataFileRule complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DataFileRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://visualisations.acuity.com/DataTransformation}NamedRule">
 *       &lt;sequence>
 *         &lt;element name="entity" type="{http://visualisations.acuity.com/DataTransformation}EntityRule" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://visualisations.acuity.com/DataTransformation}fileType" default="Cumulative" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataFileRule", propOrder = {
        "entity"
})
public class DataFileRule
        extends NamedRule {

    protected List<EntityRule> entity;
    @XmlAttribute
    protected FileType type;
    private FileStandard standard;

    /**
     * Gets the value of the entity property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entity property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntity().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityRule }
     */
    public List<EntityRule> getEntity() {
        if (entity == null) {
            entity = new ArrayList<EntityRule>();
        }
        return this.entity;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     *         {@link FileType }
     */
    public FileType getType() {
        if (type == null) {
            return FileType.CUMULATIVE;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link FileType }
     */
    public void setType(FileType value) {
        this.type = value;
    }

    public void setStandard(FileStandard standard) {
        this.standard = standard;
    }

    public FileStandard getStandard() {
        return standard;
    }
}
