//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 02:29:23 PM MSK 
//


package com.acuity.visualisations.transform.rule;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parserRule.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="parserRule">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DayFirst"/>
 *     &lt;enumeration value="MonthFirst"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "parserRule")
@XmlEnum
public enum ParserRule {

    @XmlEnumValue("DayFirst")
    DAY_FIRST("DayFirst"),
    @XmlEnumValue("MonthFirst")
    MONTH_FIRST("MonthFirst");
    private final String value;

    ParserRule(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParserRule fromValue(String v) {
        for (ParserRule c : ParserRule.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
