/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 02:29:23 PM MSK 
//


package com.acuity.visualisations.transform.rule;

import com.acuity.visualisations.batch.holders.configuration.IStudyRule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for StudyRule complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="StudyRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://visualisations.acuity.com/DataTransformation}NamedRule">
 *       &lt;sequence>
 *         &lt;element name="file" type="{http://visualisations.acuity.com/DataTransformation}DataFileRule" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="checkStudyCode" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudyRule", propOrder = {
        "file"
})
public class StudyRule
        extends NamedRule implements IStudyRule {

    protected Long id;

    protected List<DataFileRule> file;

    @XmlAttribute
    protected String displayName;

    @XmlAttribute
    protected Boolean checkStudyCode;

    /**
     * Gets the value of the file property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFile().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link DataFileRule }
     */
    public List<DataFileRule> getFile() {
        if (file == null) {
            file = new ArrayList<DataFileRule>();
        }
        return this.file;
    }

    /* (non-Javadoc)
     * @see com.acuity.visualisations.transform.rule.IStudyRule#getDisplayName()
    */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /* (non-Javadoc)
     * @see com.acuity.visualisations.transform.rule.IStudyRule#isCheckStudyCode()
	 */
    public boolean isCheckStudyCode() {
        if (checkStudyCode == null) {
            return true;
        } else {
            return checkStudyCode;
        }
    }

    /**
     * Sets the value of the checkStudyCode property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setCheckStudyCode(Boolean value) {
        this.checkStudyCode = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
