//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 08:28:32 PM MSK 
//


package com.acuity.visualisations.transform.ndtrule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for NDTFileViewsRule complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="NDTFileViewsRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/NewDataTransformation}NDTNamedRule">
 *       &lt;sequence>
 *         &lt;element name="fileView" type="{http://www.example.org/NewDataTransformation}NDTFileViewRule" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NDTFileViewsRule", propOrder = {
        "fileView"
})
public class NDTFileViewsRule
        extends NDTNamedRule {

    protected List<NDTFileViewRule> fileView;

    /**
     * Gets the value of the fileView property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileView property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileView().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link NDTFileViewRule }
     */
    public List<NDTFileViewRule> getFileView() {
        if (fileView == null) {
            fileView = new ArrayList<NDTFileViewRule>();
        }
        return this.fileView;
    }

}
