/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 08:28:32 PM MSK 
//


package com.acuity.visualisations.transform.ndtrule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NDTStudyRule complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="NDTStudyRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/NewDataTransformation}NDTNamedRule">
 *       &lt;sequence>
 *         &lt;element name="files" type="{http://www.example.org/NewDataTransformation}NDTFilesRule"/>
 *         &lt;element name="fileViews" type="{http://www.example.org/NewDataTransformation}NDTFileViewsRule"/>
 *         &lt;element name="entities" type="{http://www.example.org/NewDataTransformation}NDTEntitiesRule"/>
 *       &lt;/sequence>
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="checkStudyCode" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NDTStudyRule", propOrder = {
        "files",
        "fileViews",
        "entities"
})
public class NDTStudyRule
        extends NDTNamedRule {

    @XmlElement(required = true)
    protected NDTFilesRule files;
    @XmlElement(required = true)
    protected NDTFileViewsRule fileViews;
    @XmlElement(required = true)
    protected NDTEntitiesRule entities;
    @XmlAttribute
    protected String displayName;

    @XmlAttribute
    protected Boolean checkStudyCode;

    /**
     * Gets the value of the files property.
     *
     * @return possible object is
     *         {@link NDTFilesRule }
     */
    public NDTFilesRule getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     *
     * @param value allowed object is
     *              {@link NDTFilesRule }
     */
    public void setFiles(NDTFilesRule value) {
        this.files = value;
    }

    /**
     * Gets the value of the fileViews property.
     *
     * @return possible object is
     *         {@link NDTFileViewsRule }
     */
    public NDTFileViewsRule getFileViews() {
        return fileViews;
    }

    /**
     * Sets the value of the fileViews property.
     *
     * @param value allowed object is
     *              {@link NDTFileViewsRule }
     */
    public void setFileViews(NDTFileViewsRule value) {
        this.fileViews = value;
    }

    /**
     * Gets the value of the entities property.
     *
     * @return possible object is
     *         {@link NDTEntitiesRule }
     */
    public NDTEntitiesRule getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     *
     * @param value allowed object is
     *              {@link NDTEntitiesRule }
     */
    public void setEntities(NDTEntitiesRule value) {
        this.entities = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the checkStudyCode property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isCheckStudyCode() {
        if (checkStudyCode == null) {
            return true;
        } else {
            return checkStudyCode;
        }
    }

    /**
     * Sets the value of the checkStudyCode property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setCheckStudyCode(Boolean value) {
        this.checkStudyCode = value;
    }

}
