/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 08:28:32 PM MSK 
//


package com.acuity.visualisations.transform.ndtrule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.acuity.visualisations.transform.ndtrule package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName ROOT_QNAME = new QName("http://www.example.org/NewDataTransformation", "root");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.acuity.visualisations.transform.ndtrule
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NDTFilesRule }
     */
    public NDTFilesRule createNDTFilesRule() {
        return new NDTFilesRule();
    }

    /**
     * Create an instance of {@link NDTNamedRule }
     */
    public NDTNamedRule createNDTNamedRule() {
        return new NDTNamedRule();
    }

    /**
     * Create an instance of {@link NDTFileRule }
     */
    public NDTFileRule createNDTFileRule() {
        return new NDTFileRule();
    }

    /**
     * Create an instance of {@link NDTFileViewsRule }
     */
    public NDTFileViewsRule createNDTFileViewsRule() {
        return new NDTFileViewsRule();
    }

    /**
     * Create an instance of {@link NDTFilterRule }
     */
    public NDTFilterRule createNDTFilterRule() {
        return new NDTFilterRule();
    }

    /**
     * Create an instance of {@link NDTColumnRule }
     */
    public NDTColumnRule createNDTColumnRule() {
        return new NDTColumnRule();
    }

    /**
     * Create an instance of {@link NDTEntitiesRule }
     */
    public NDTEntitiesRule createNDTEntitiesRule() {
        return new NDTEntitiesRule();
    }

    /**
     * Create an instance of {@link NDTProjectRule }
     */
    public NDTProjectRule createNDTProjectRule() {
        return new NDTProjectRule();
    }

    /**
     * Create an instance of {@link NDTViewColumnRule }
     */
    public NDTViewColumnRule createNDTViewColumnRule() {
        return new NDTViewColumnRule();
    }

    /**
     * Create an instance of {@link NDTEntityRule }
     */
    public NDTEntityRule createNDTEntityRule() {
        return new NDTEntityRule();
    }

    /**
     * Create an instance of {@link NDTFileViewRule }
     */
    public NDTFileViewRule createNDTFileViewRule() {
        return new NDTFileViewRule();
    }

    /**
     * Create an instance of {@link NDTRootRule }
     */
    public NDTRootRule createNDTRootRule() {
        return new NDTRootRule();
    }

    /**
     * Create an instance of {@link NDTViewEntityRule }
     */
    public NDTViewEntityRule createNDTViewEntityRule() {
        return new NDTViewEntityRule();
    }

    /**
     * Create an instance of {@link NDTStudyRule }
     */
    public NDTStudyRule createNDTStudyRule() {
        return new NDTStudyRule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NDTRootRule }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.example.org/NewDataTransformation", name = "root")
    public JAXBElement<NDTRootRule> createRoot(NDTRootRule value) {
        return new JAXBElement<NDTRootRule>(ROOT_QNAME, NDTRootRule.class, null, value);
    }

}
