/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.02 at 02:46:40 PM MSK 
//


package com.acuity.visualisations.transform.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityReferedByRule complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="EntityReferedByRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://visualisations.acuity.com/EntitiesDescription}EntityFieldSetRule">
 *       &lt;attribute name="equalToUniqueSet" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityReferedByRule")
public class EntityReferedByRule
        extends EntityFieldSetRule {

    @XmlAttribute
    protected Boolean equalToUniqueSet;

    /**
     * Gets the value of the equalToUniqueSet property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isEqualToUniqueSet() {
        if (equalToUniqueSet == null) {
            return false;
        } else {
            return equalToUniqueSet;
        }
    }

    /**
     * Sets the value of the equalToUniqueSet property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setEqualToUniqueSet(Boolean value) {
        this.equalToUniqueSet = value;
    }

}
